### ISSUE TITLE
Trained weights?

### ISSUE THREAD

**Issue by fcakyon** [lucifer443/SpineNet-Pytorch#2]
First off all, thanks a lot for the pytorch implementation, I think it's only port atm.

Do you have any plans on publishing your trained weights?

**Comment by lucifer443** [comment]
For some reason, I can't release the model. But you can reproduce the result easily using the config file that I provide.

**Comment by lucifer443** [comment]
> First off all, thanks a lot for the pytorch implementation, I think it's only port atm.
> 
> Do you have any plans on publishing your trained weights?

For some reason, I can't release the model. But you can reproduce the result easily using the config file that I provide.

**Comment by yan-roo** [comment]
@fcakyon 
https://github.com/yan-roo/SpineNet-Pytorch
