### ISSUE TITLE
ImportError: ConvModule missing

### ISSUE THREAD

**Issue by Alexandre-Delplanque** [lucifer443/SpineNet-Pytorch#3]
Hello!

I tried to use your code to train on my own dataset, but it seems that the module ```ConvModule``` is missing ([spinenet.py-L5](https://github.com/lucifer443/SpineNet-Pytorch/blob/master/mmdet/models/backbones/spinenet.py#L5)) in [mmdetection/mmdet/ops](https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops).

Thank you in advance for your help.

**Comment by lucifer443** [comment]
> Hello!
> I tried to use your code to train on my own dataset, but it seems that the module ConvModule is missing (spinenet.py-L5) in mmdetection/mmdet/ops.
> Thank you in advance for your help.

Please check out the version of your mmdetection, I use 1.1.0 version.

**Comment by Alexandre-Delplanque** [comment]
I use 1.1.0 version too

**Comment by LetsGoFir** [comment]
> I use 1.1.0 version too

How dow you fix it, please?
